### ISSUE TITLE
print_array can be replaced with println!

### ISSUE THREAD

**Issue by emoon** [zigguratvertigo/rust-sort#2]
This code

https://github.com/zigguratvertigo/rust-sort/blob/master/src/common.rs#L10-L14

And used like this:

https://github.com/zigguratvertigo/rust-sort/blob/master/src/bubblesort.rs#L23-L25

Can be replaced with

```Rust
println!("Original: {:?}\n", &values);
```

This is because many types in Rust implements the Debug trait which is quite awesome https://doc.rust-lang.org/std/fmt/trait.Debug.html

Just a hint :)

**Comment by zigguratvertigo** [comment]
Nice, thanks!!

**Comment by zigguratvertigo** [comment]
Fixed here, https://github.com/zigguratvertigo/rust-sort/commit/f4c4a9014e2fd87e4292bad9109218449d54818a

Thanks!!
